installerInfo: '{ "productId": "Helm_prometheus_artifactory/{{ .Chart.Version }}", "features": [ { "featureId": "ArtifactoryVersion/{{ default .Chart.AppVersion .Values.artifactory.image.version }}" }, { "featureId": "{{ if .Values.postgresql.enabled }}postgresql{{ else }}{{ .Values.database.type }}{{ end }}/0.0.0" }, { "featureId": "Platform/{{ default "kubernetes" .Values.installer.platform }}" },  { "featureId": "Channel/Helm_prometheus_artifactory" } ] }'
artifactory:
  customInitContainersBegin: |
    volumes:
    - name: fluentd-sidecar-configmap
      configMap:
        name: "artifactory-fluentd-sidecar-configmap"
    - name: "prepare-fluentd-conf-on-persistent-volume"
      image: "{{ .Values.initContainerImage }}"
      imagePullPolicy: "{{ .Values.artifactory.image.pullPolicy }}"
      volumeMounts:
        - mountPath: {{ .Values.artifactory.persistence.mountPath }}/etc/fluentd/fluentd.conf
          name: fluentd-sidecar-configmap     
  customSidecarContainers: |
    - name: "artifactory-fluentd-sidecar"
      image: "partnership-public-images.jfrog.io/fluentd/fluentd:1.13.2"
      imagePullPolicy: "IfNotPresent"
      volumeMounts:
        - mountPath: "{{ .Values.artifactory.persistence.mountPath }}"
          name: volume
      env:
        - name: JF_PRODUCT_DATA_INTERNAL
          value: {{ .Values.artifactory.persistence.mountPath }}
        - name: FLUENTD_CONF
          value: ../../../../{{ .Values.artifactory.persistence.mountPath }}/etc/fluentd/fluentd.conf

## Allows to add additional kubernetes resources
## Use --- as a separator between multiple resources
## For an example, refer - https://github.com/jfrog/log-analytics-prometheus
additionalResources: |
  apiVersion: v1
  kind: ConfigMap
  metadata:
    name: "artifactory-fluentd-sidecar-configmap"
  data:
    fluent.conf.rt: |-
  {{ .Files.Get "fluent.conf.stdout.rt" | indent 4}}
 
